### ISSUE TITLE
Control API Init Job failed to initialize the mesh

### ISSUE THREAD

**Issue by chrisbsmith** [greymatter-io/helm-charts#862] opened 2021-01-20 21:49 UTC
While working with a customer to deploy Grey Matter 1.3 into an OCP 4.6.9 cluster, we noticed that the mesh did not appear to be configured after the init job started. We exec'd into a few container and noticed that there were no clusters or certs loaded into envoy. We then looked at the logs of the control service and found that it was throwing errors about missing proxies.  

The init job reported that it succeeded successfully even though the mesh was not configured as expected.

When deleted the job and then ran a helm upgrade command. This rebuilt the init job. We tailed the logs and the init script threw a lot of `400` errors. However, after the init job, the mesh was configured as expected.

**Comment by dgoldstein1** [comment] 2021-01-21 01:49
Yup this is a duplicate of 814 and 841

**Comment by dgoldstein1** [comment] 2021-01-21 21:28
closed by https://github.com/greymatter-io/helm-charts/pull/851

**Closed by dgoldstein1** 2021-01-21 21:28 UTC
Labels: bug, ocp-4.6
